### ISSUE TITLE
[proposal] visuals.SpinnerPromise

### ISSUE THREAD

**Issue by lekkas** [balena-io-modules/resin-cli-visuals#39]
``` coffeescript
###*
    # @summary Create a CLI Spinner that spins on a promise
    # @name SpinnerPromise
    # @class
    # @public
    # @memberof visuals
    #
    # @description
    # This function will start a Spinner and stop it when the
    # passed promise is either fulfilled or rejected. The function
    # returns a promise that is is resolved with the passed
    # promise's value.
    #
    # @param {Promise} promise - promise to spin upon
    # @param {String} startMessage - start spinner message
    # @param {String} stopMessage - stop spinner message
    # @fulfil {Object} value - resolved 'promise' value
    # @returns {Promise}
    #
    # @throws Will stop spinner and throw on 'promise' rejection
    #
    # @example
    #  visuals.SpinnerPromise
    #    scanDevicesPromise
    #    "Scanning devices"
    #    "Scanned devices"
    #  .then (devices) ->
    #    console.log devices
    ###
```

@jviotti do you think it'd make sense to have this function PRed here? https://github.com/resin-io-modules/resin-sync/blob/master/lib/utils.coffee#L125-L138

**Comment by jviotti** [comment]
Looks good, however I'd integrate these changes into `visuals.Spinner` itself rather than creating a new class. What about accepting an optional promise as an argument to the `.start()` method, and make such method be resolved/rejected based on the input promise, and `.stop()` automatically when necessary?

Also, the "stop" message should be handled by the client IMHO.

For example:

``` coffee
spinner = new visuals.Spinner("Scanning devices")
spinner.start(scanDevicesPromise).then ->
  console.log('Scanned devices')
  console.log('Spinner also stopped')
.catch ->
  console.log('An error happened')
  console.log('Spinner was also stopped')
```

**Comment by lekkas** [comment]
> Also, the "stop" message should be handled by the client IMHO.

This was one of the things I wanted to avoid actually :P . If the passed promise is resolved, and a 'stopMessage' has been provided, it would save module users from adding an extra `.then()` method call just to print their success message.

Passing an optional promise in `.start()` would work, but that would make the API inconsistent: in the synchronous version the `.start()` will be followed by a matching `.stop()`, while when a promise is passed `.stop()` will be implied . Hence the proposal of having a separate class for this feature.

**Comment by jviotti** [comment]
I see, lets added it then, by accepting an options object containing both `startMessage` and `stopMessage` so its clear from the user point of view which message corresponds to what.
